@GrabConfig(systemClassLoader = true)
@Grab('org.hsqldb:hsqldb:2.3.3')

import groovy.sql.Sql

def connection = 'jdbc:hsqldb:mem:tmpDB'
def user = 'sa'
def password = ''
def driver = 'org.hsqldb.jdbcDriver'

Sql.withInstance(connection, user, password, driver) { sql ->
    sql.execute '''
        CREATE TABLE groovy_projects (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL
        )'''


    def projects = ['Grails', 'Gradle', 'Spock']
    projects.each { name ->
        def newKeys = sql.executeInsert """
        INSERT INTO groovy_projects (name)
        VALUES (${name})"""

        println "New key created: $newKeys"
    }
}
